### ISSUE TITLE
DeepState.hpp fails to compile with GCC -O0

### ISSUE THREAD

**Issue by laurynas-biveinis** [trailofbits/deepstate#375] opened 2021-03-25 04:39 UTC
The source file can be reduced to only including DeepState.hpp:
````c++
#include <deepstate/DeepState.hpp>
````
If compiled with -O0:
````
$ /usr/local/opt/gcc/bin/g++-10 -std=c++11 -c -O0 foo.cpp -isystem src/include
In file included from src/include/deepstate/DeepState.hpp:20,
                 from foo.cpp:1:
src/include/deepstate/DeepState.h: In function 'size_t deepstate::PickIndex(double*, size_t)':
src/include/deepstate/DeepState.h:392:1: error: inlining failed in call to 'always_inline' 'uint32_t DeepState_UIntInRange(uint32_t, uint32_t)': function not considered for inlining
  392 | DEEPSTATE_MAKE_SYMBOLIC_RANGE(UInt, uint32_t)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/include/deepstate/DeepState.h:392:1: note: called from here
  392 | DEEPSTATE_MAKE_SYMBOLIC_RANGE(UInt, uint32_t)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

Compiling with -O1 is enough not to trigger the issue. Clang also works at -O0.

**Comment by agroce** [comment] 2021-04-25 18:18
We're investigating, have reproduced on ubuntu.  Looks like g++ 10.2 doesn't have this problem, but g++ 10.3 does.

**Comment by agroce** [comment] 2021-04-25 20:10
This seems to have somehow been fixed by the PR from @kosak -- closing.  @laurynas-biveinis can you confirm fixed?

**Closed by agroce** 2021-04-25 20:10 UTC

**Comment by laurynas-biveinis** [comment] 2021-04-26 06:42
@agroce confirmed fixed, thank you
